### PR TITLE
Add the free state project [pending FSP id]

### PR DESCRIPTION
**Pull request by kauffj**

### CODE REVIEW

**Comment by Marmaladepen** [comment]
Looks good. Once we have the FSP's affiliate code, I'll merge this. Thanks!

**Comment by kauffj** [comment]
How did you find these? They have a public Smile page. I put out a request
which was acknowledged, but it's still working it's way to someone that
actually understands it.

On Mon, Jan 25, 2016 at 5:37 PM, Marmaladepen notifications@github.com
wrote:

> Looks good. Once we have the FSP's affiliate code, I'll merge this. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marmaladepen/liberty-amazon-donator/pull/1#issuecomment-174703316
> .

## 

[image: TopScore] http://www.usetopscore.com/

Jeremy Kauffman, CEO
(267) 777-7592

[image: Twitter] https://twitter.com/usetopscore [image: Linkedin]
https://www.linkedin.com/company/topscore-inc-

**Comment by Marmaladepen** [comment]
I believe it's a different program than the Smile program. They'd need to sign up if they are not already. Glad you contacted them. Thanks.

**Comment by kauffj** [comment]
Hey, this one has been staring at me for a while and I'm still crazy busy.
Are you still planning to work on and/or promote this?

Jeremy Kauffman, CEO
(267) 777-7592

[image: Twitter] https://twitter.com/usetopscore [image: Linkedin]
https://www.linkedin.com/company/topscore-inc-

**Pull request closed without merging**
